name: larm
channels:
  - conda-forge
  - defaults
  - pytorch
  - nvidia
dependencies:
  - python=3.10
  - easydict=1.13
  - einops=0.8.0
  - imageio=2.35.1
  - kornia=0.7.3
  - matplotlib=3.9.2
  - numpy=1.26.4
  - open3d=0.19.0
  - opencv
  - pip=24.2
  - pytorch=2.2.0
  - pytorch-cuda=12.1
  - pyyaml=6.0.2
  - requests=2.31.0
  - safetensors=0.4.5
  - scikit-learn=1.5.2
  - scipy=1.14.1
  - tokenizers=0.20.0
  - torchvision=0.17.0 
  - torchaudio=2.2.0
  - tqdm=4.65.0
  - transformers=4.45.1
  - transforms3d=0.4.2
  - trimesh=4.4.9
  - urdfpy=0.0.22
  - pip:
      - calibur==0.0.1
      - lpips==0.1.4
      - mathutils==3.3.0
      - "networkx>=2.8,<3"
      - OpenEXR==3.3.4
      - torchmetrics==1.4.0.post0
      - torcheval==0.0.7
      - wandb
      - yacs
