dataset:
  train_data: ../../partnet-mobility-render-norm-0/data_train.txt
  eval_data: ../../partnet-mobility-render-norm-0/data_eval.txt
  num_input_views: 6
  num_target_views: 1
  resolution: 512
  part_finetune: true

model:
  hidden: 768
  num_layers: 12
  patch_size: 8
  linear_dim: 4096

training:
  batch_size: 2
  eval_batch_size: 18
  num_data_workers: 8
  training_prefetch: 4
  lr: 0.0001
  beta1: 0.9
  beta2: 0.95
  weight_decay: 0.05
  clip_norm: 1.0
  num_iters: 200000
  warmup_steps: 2500
  vis_interval: 200
  log_interval: 1
  eval_interval: 2000
  save_interval: 2000
  save_dir: "./exp/test"
  vis_dir: "./exp/vis_test"
  resume_ckpt: ./exp/checkpoints_objaverse_12_full_7/model_55000.pth
  resume_iter: null
  upload: false
  s3_bucket: partnet-mobility-info

loss:
  weight: 0.1
  depth_weight: 2.0

wandb:
  project: larm-debugging
  run_id: null
  key: ""  # Insert your wandb API key here
